### ISSUE TITLE
403 when verifying a mfa token

### ISSUE THREAD

**Issue by lancehudson** [chrismalek/oktasdk-go#7]
I am using Hashicorp Vault. I've been testing using a read only administrative api token to pull group memberships. Vault configures the Okta client with an api token when it creates it. The client sends the api token (authorization header) with every request.

If you use a read only admin api token to call 

> POST https://dev-bbb-admin.oktapreview.com/api/v1/authn/factors/xxx/verify
> Authorization: SSWS xxxxyyyyzzzz
>
> {
>	"stateToken": "XXXXYYYYZZZZ"
>}

 it fails with

> HTTP 403
> {
>    "errorCode": "E0000006",
>    "errorSummary": "You do not have permission to perform the requested action",
>    "errorLink": "E0000006",
>    "errorId": "XXXXXXXX",
>    "errorCauses": []
>}

but it succeeds if the authorization header is not sent.

Is it possible to setup the client to not send the authorization header on these requests?
I am reaching out to Okta to see if they can fix it on their end.

**Comment by chrismalek** [comment]
I am confused. I don't have the factor/verify endpoint implemented in this SDK.  Do you happen to be confusing it with the official SDK from OKTA that is under development https://github.com/okta/okta-sdk-golang

**Comment by lancehudson** [comment]
Hi, Hashicorp vault is using your library, and I guess they use your underlying client to do the factor/verify calls.

https://github.com/hashicorp/vault/blob/v1.0.0/builtin/credential/okta/backend.go#L169

**Comment by chrismalek** [comment]
I added some code to not include the Authorization header if there is no API token. Most of my use of this library so far was doing admin actions. It looks like Hashicorp is using it for some other user cases I had not hit yet. They are actually using some of the raw API to construct the verification calls to OKTA.
